backend:
  name: git-gateway
  branch: master

display_url: https://neo035.fr

logo_url: /img/logo.png

media_folder: static/img
public_folder: /img

collections:
  - name: 'config'
    label: 'Configuration'
    delete: false
    editor:
      preview: false
    files:
      - name: 'toml'
        label: 'Netlify TOML'
        description: 'The netlify.toml file is your configuration file on how Netlify will build and deploy your site — including redirects, branch and context specific settings, and much more.'
        file: 'netlify.toml'
        fields:
          - label: 'Build'
            name: 'build'
            widget: 'object'
            fields:
              - label: 'Environment'
                name: 'environment'
                widget: 'object'
                fields:
                  - {
                      label: 'Yarn version',
                      name: 'YARN_VERSION',
                      widget: 'string',
                    }
                  - {
                      label: 'Yarn flags',
                      name: 'YARN_FLAGS',
                      widget: 'string',
                    }
                  - {
                      label: 'Node options',
                      name: 'NODE_OPTIONS',
                      widget: 'string',
                    }
          - label: 'Redirects'
            name: 'redirects'
            label_singular: 'redirection'
            widget: 'list'
            fields:
              - { label: 'From', name: 'from', widget: 'string' }
              - { label: 'To', name: 'to', widget: 'string' }
              - label: 'Status'
                name: 'status'
                widget: 'select'
                default: 301
                options:
                  - { label: 'Moved Permanently (301)', value: 301 }
                  - { label: 'Found (302)', value: 302 }
                  - { label: 'Not Found (404)', value: 404 }
                  - { label: 'OK (200)', value: 200 }
                hint: 'The default HTTP status code is 301, but you can define a different one.'
              - label: 'Force'
                name: 'force'
                widget: 'boolean'
                default: true
                hint: "By default, redirects won't be applied if there's a file with the same path as the one defined in the `from` property. Setting `force` to `true` will make the redirect rule take precedence over any existing files."
      - name: 'json'
        label: 'Configuration'
        file: 'config.json'
        fields:
          - { label: 'Site Title', name: 'siteTitle', widget: 'string' }
          - { label: 'Name', name: 'manifestName', widget: 'string' }
          - { label: 'Short Name', name: 'manifestShortName', widget: 'string' }
          - {
              label: 'Start Url',
              name: 'manifestStartUrl',
              widget: 'hidden',
              default: '/',
            }
          - {
              label: 'Theme Color',
              name: 'manifestThemeColor',
              widget: 'string',
            }
          - { label: 'Display', name: 'manifestDisplay', widget: 'string' }
          - { label: 'Icon', name: 'manifestIcon', widget: 'image' }
          - {
              label: 'Prefix',
              name: 'pathPrefix',
              widget: 'hidden',
              default: '/',
            }
          - { label: 'Owner Name', name: 'ownerName', widget: 'string' }
          - { label: 'Channel ID', name: 'channelId', widget: 'string' }
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - label: 'Social Links'
            name: 'socialLinks'
            widget: 'list'
            fields:
              - { label: 'Icon', name: 'icon', widget: 'string' }
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
  - name: 'translations'
    label: 'Translations'
    delete: false
    editor:
      preview: false
    files:
      - name: 'french'
        label: 'French'
        file: 'src/translations/fr.json'
        fields:
          - label: 'Home'
            name: 'home'
            widget: 'object'
            fields:
              - { label: 'Sidebar title', name: 'nav', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Show me', name: 'showMe', widget: 'string' }
          - label: 'events'
            name: 'events'
            widget: 'object'
            fields:
              - { label: 'Sidebar title', name: 'nav', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'edescription', widget: 'string' }
          - label: 'Videos'
            name: 'videos'
            widget: 'object'
            fields:
              - { label: 'Sidebar title', name: 'nav', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'edescription', widget: 'string' }
          - label: 'FAQ'
            name: 'faq'
            widget: 'object'
            fields:
              - { label: 'Sidebar title', name: 'nav', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Show me', name: 'showMe', widget: 'string' }
              - { label: 'Questions', name: 'questions', widget: 'string' }
              - { label: 'Time', name: 'time', widget: 'string' }
          - label: 'Partners'
            name: 'partners'
            widget: 'object'
            fields:
              - { label: 'Sidebar title', name: 'nav', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'edescription', widget: 'string' }
          - label: 'Contact'
            name: 'contact'
            widget: 'object'
            fields:
              - { label: 'Sidebar title', name: 'nav', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'edescription', widget: 'string' }
              - label: 'Form'
                name: 'form'
                widget: 'object'
                fields:
                  - { label: 'Error message', name: 'error', widget: 'string' }
                  - {
                      label: 'Success message',
                      name: 'success',
                      widget: 'string',
                    }
                  - {
                      label: 'Loading message',
                      name: 'loading',
                      widget: 'string',
                    }
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - { label: 'Age', name: 'age', widget: 'string' }
                  - { label: 'Mail', name: 'mail', widget: 'string' }
                  - { label: 'Message', name: 'message', widget: 'string' }
                  - { label: 'Required', name: 'required', widget: 'string' }
                  - {
                      label: 'Invalid Age',
                      name: 'invalidAge',
                      widget: 'string',
                    }
                  - {
                      label: 'Invalid Mail',
                      name: 'invalidMail',
                      widget: 'string',
                    }
                  - { label: 'Submit', name: 'submit', widget: 'string' }
          - label: 'Footer'
            name: 'footer'
            widget: 'object'
            fields:
              - {
                  label: 'Mentions légales',
                  name: 'legalNotices',
                  widget: 'string',
                }
              - { label: 'Copyright', name: 'copyright', widget: 'string' }
          - label: 'Page Metadata'
            name: 'pageMetadata'
            widget: 'object'
            fields:
              - label: 'Home'
                name: 'home'
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - {
                      label: 'Description',
                      name: 'description',
                      widget: 'string',
                    }
              - label: 'Legal Notices'
                name: 'legalNotices'
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - {
                      label: 'Description',
                      name: 'description',
                      widget: 'string',
                    }
  - name: 'events'
    label: 'Events'
    label_singular: 'event'
    folder: 'src/data/events'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'External link', name: 'link', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'faq'
    label: 'FAQ'
    label_singular: 'faq'
    folder: 'src/data/faq'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Youtube Link', name: 'link', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
      - label: 'Questions'
        name: 'link'
        widget: 'list'
        fields:
          - { label: 'Label', name: 'label', widget: 'string' }
          - { label: 'Time', name: 'time', widget: 'string' }
