backend:
  name: git-gateway
  branch: master

display_url: https://neo035.fr

logo_url: /img/logo.png

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

locale: fr

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'config'
    label: 'Configuration'
    delete: false
    editor:
      preview: false
    files:
      - name: 'configJson'
        label: 'Paramètres et métadonnées'
        file: 'config.json'
        fields:
          - { label: 'Site Title', name: 'siteTitle', widget: 'string' }
          - { label: 'Job Title', name: 'jobTitle', widget: 'string' }
          - { label: 'Name', name: 'siteName', widget: 'string' }
          - {
              label: 'Theme Color (App bar on mobile)',
              name: 'themeColor',
              widget: 'string',
            }
          - { label: 'Owner Name', name: 'ownerName', widget: 'string' }
          - { label: 'Channel ID', name: 'channelId', widget: 'string' }
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - label: 'Social Links'
            name: 'socialLinks'
            widget: 'list'
            fields:
              - { label: 'Icon', name: 'icon', widget: 'string' }
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
          - label: 'Playlists'
            name: 'playlists'
            widget: 'list'
          - {
              label: 'FAQ Playlist ID',
              name: 'faqPlaylistId',
              widget: 'string',
            }
          - {
              label: 'Easter Egg Link',
              name: 'easterEggLink',
              widget: 'string',
              hint: 'KONAMI Code : up up down down left right left right b a',
            }
  - name: 'translations'
    label: 'Traductions'
    folder: 'src/translations'
    format: 'json'
    identifier_field: 'title'
    delete: false
    editor:
      preview: false
    fields:
      - {
          label: 'FileName',
          name: 'title',
          widget: 'string',
          hint: 'Translation title in this CMS application. Examples: "French", "English"',
        }
      - label: 'Home'
        name: 'home'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
          - { label: 'Show me', name: 'showMe', widget: 'string' }
          - { label: 'Go Back Home', name: 'goBackHome', widget: 'string' }
      - label: 'About'
        name: 'about'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
      - label: 'Events'
        name: 'events'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - {
              label: 'No event scheduled (message)',
              name: 'noEventScheduled',
              widget: 'string',
            }
      - label: 'Videos'
        name: 'videos'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: 'Watch playlist', name: 'watchPlaylist', widget: 'string' }
      - label: 'FAQ'
        name: 'faq'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - { label: 'Show me', name: 'showMe', widget: 'string' }
          - { label: 'FAQ not found', name: 'noFaqItems', widget: 'string' }
          - {
              label: 'Search Placeholder',
              name: 'searchPlaceholder',
              widget: 'string',
            }
          - { label: 'Watch video', name: 'watchVideo', widget: 'string' }
          - { label: 'Published at', name: 'publishedAt', widget: 'string' }
          - { label: 'Questions', name: 'questions', widget: 'string' }
          - { label: 'Time', name: 'time', widget: 'string' }
      - label: 'ERRATA Page'
        name: 'errata'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Show me', name: 'showMe', widget: 'string' }
      - label: 'Partners'
        name: 'partners'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Contact'
        name: 'contact'
        widget: 'object'
        fields:
          - { label: 'Sidebar title', name: 'nav', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
          - label: 'Form'
            name: 'form'
            widget: 'object'
            fields:
              - { label: 'Error message', name: 'error', widget: 'string' }
              - { label: 'Success message', name: 'success', widget: 'string' }
              - { label: 'Loading message', name: 'loading', widget: 'string' }
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Age', name: 'age', widget: 'string' }
              - { label: 'Mail', name: 'mail', widget: 'string' }
              - { label: 'Message', name: 'message', widget: 'string' }
              - { label: 'Submit', name: 'submit', widget: 'string' }
      - label: 'Not Found'
        name: 'notFound'
        widget: 'object'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Footer'
        name: 'footer'
        widget: 'object'
        fields:
          - {
              label: 'Mentions légales',
              name: 'legalNotices',
              widget: 'string',
            }
          - { label: 'Copyright', name: 'copyright', widget: 'string' }
      - label: 'Page Metadata'
        name: 'pageMetadata'
        widget: 'object'
        fields:
          - label: 'Home'
            name: 'home'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'ERRATA'
            name: 'errata'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'FAQ'
            name: 'faq'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
          - label: 'Legal Notices'
            name: 'notices'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'events'
    label: 'Evénements'
    label_singular: 'événement'
    folder: 'src/data/events'
    identifier_field: 'identifier'
    create: true
    path: '{{identifier}}/index_{{lang}}'
    summary: '[{{lang}}] {{identifier}}'
    view_filters:
      - label: 'Français'
        field: lang
        pattern: 'fr'
      - label: 'Anglais'
        field: lang
        pattern: 'en'
    editor:
      preview: false
    fields:
      - { label: 'Key', name: 'key', widget: 'hidden', default: 'event' }
      - { label: 'Identifiant', name: 'identifier', widget: 'string' }
      - {
          label: 'Lang',
          name: 'lang',
          widget: 'select',
          default: 'fr',
          options:
            [
              { label: 'Français', value: 'fr' },
              { label: 'English', value: 'en' },
            ],
        }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'External link', name: 'link', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'errata'
    label: 'ERRATA'
    folder: 'src/data/errata'
    identifier_field: 'identifier'
    create: true
    path: '{{identifier}}/index_{{lang}}'
    summary: '[{{lang}}] {{identifier}}'
    view_filters:
      - label: 'Français'
        field: lang
        pattern: 'fr'
      - label: 'Anglais'
        field: lang
        pattern: 'en'
    editor:
      preview: false
    fields:
      - { label: 'Key', name: 'key', widget: 'hidden', default: 'errata' }
      - { label: 'Identifiant', name: 'identifier', widget: 'string' }
      - {
          label: 'Lang',
          name: 'lang',
          widget: 'select',
          default: 'fr',
          options:
            [
              { label: 'Français', value: 'fr' },
              { label: 'English', value: 'en' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Video link', name: 'link', widget: 'string' }
      - { label: 'Errors', name: 'body', widget: 'markdown' }
  - name: 'notices'
    label: 'Mentions'
    label_singular: 'notice'
    folder: 'src/data/notices'
    path: 'index_{{lang}}'
    create: false
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'home'
    label: 'Accueil'
    folder: 'src/data/home'
    path: 'index_{{lang}}'
    create: false
    editor:
      preview: false
    fields:
      - { label: 'Key', name: 'key', widget: 'hidden', default: 'home' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'A propos'
    folder: 'src/data/about'
    path: 'index_{{lang}}'
    create: false
    editor:
      preview: false
    fields:
      - { label: 'Key', name: 'key', widget: 'hidden', default: 'about' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
